---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  fig.dev = "grDevices::png",
  dpi = 300L,
  dev.args = list(),
  fig.ext = "png",
  fig.retina = 2L,
  fig.align = "center"
)
```

# clusterlayouts

Graph layouts using cluster information. The function calculates a grouped layout based on the node attribute in `igraph` or `tbl_graph` object, while respecting the original edge attributes.

```{r, warning=FALSE, message=FALSE, fig.height=4, fig.width=5}
## Make an example graph and assign a random category
library(clusterlayouts)
library(igraph)
test <- igraph::random.graph.game(n=100, p=0.01)
V(test)$category <- as.factor(sample(1:4, 100, replace=TRUE))
lyt <- clusterlayouts::layout_cluster(test, "category")
ggraph(test, layout="manual", x=lyt$x, y=lyt$y)+
    geom_edge_link0(color="grey80")+
    geom_node_point(aes(color=category))+
    theme_graph()
```

```{r, fig.width=12, fig.height=10, warning=FALSE}
## Can change per cluster layout
test <- igraph::random.graph.game(n=500, p=0.001)
panel <- c(2,3,5,6,6,3,2,2)
V(test)$category <- as.factor(sample(1:sum(panel), 500, replace=TRUE))
lyt <- clusterlayouts::layout_cluster(test, "category", per_row=panel, per_layout="drl")
ggraph(test, layout="manual", x=lyt$x, y=lyt$y)+
    geom_edge_link0(color="grey80")+
    geom_node_point(aes(color=category))+
    ggfx::with_outer_glow(
        geom_node_point(aes(color=category, filter=category==29)),
        colour="gold", expand=10
    )+
    theme_graph()
```


```{r, fig.width=12, fig.height=10, warning=FALSE}
## Can align based on the column
test <- igraph::random.graph.game(n=500, p=0.001)
panel <- c(2,3,5,6,6,3,2,2)
V(test)$category <- as.factor(sample(1:sum(panel), 500, replace=TRUE))
lyt <- clusterlayouts::layout_cluster_col(test, "category", per_col=panel)
ggraph(test, layout="manual", x=lyt$x, y=lyt$y)+
    geom_edge_link0(color="grey80")+
    geom_node_point(aes(color=category))+
    ggfx::with_outer_glow(
        geom_node_point(aes(color=category, filter=category==5)),
        colour="gold", expand=10
    )+
    theme_graph()
```

```{r, fig.width=12, fig.height=10, warning=FALSE}
## Can change widths per column
test <- igraph::random.graph.game(n=1000, p=0.01)
panel <- c(2,4,3,1,5,3,6,7,2,4)
widths <- c(1,2,3,4,5,12,3,2,1,2)
V(test)$category <- as.factor(sample(1:sum(panel), 1000, replace=TRUE))
lyt <- layout_cluster_col(test, "category", 
                          per_col=panel, widths=widths)
ggraph(test, layout="manual", x=lyt$x, y=lyt$y)+
    geom_edge_link0(color="grey80")+
    geom_node_point(aes(color=category))+
    scico::scale_color_scico_d()+
    theme_graph()
```



